import type { Metadata } from "next";
import { Open_Sans as FontSans } from "next/font/google"; // Default: Poppins
import "./globals.css";
import { cn } from "@/lib/utils";
// import { Header } from "@/components/Header";
// import { Footer } from "@/components/Footer";
import { TMAProvider } from "@/providers/tma";
import { MiniApp } from "@/components/MiniApp";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased bg-[--tg-theme-background-color] text-[--tg-theme-text-color] flex flex-col",
          fontSans.variable
        )}
      >
        <TMAProvider>
          {/* <Header /> */}
          {children}
          {/* <Footer /> */}
          <MiniApp />
        </TMAProvider>
      </body>
    </html>
  );
}
